#!/usr/bin/env bash
set -e

xhost +local:root > /dev/null

nvidia-docker run -it \
    -v ${PWD}/src/ros/spirit:/root/catkin_ws/src/spirit/ \
    -v ${PWD}/src/data:/root/analysis/scripts \
    -v ${PWD}/notebooks:/root/analysis/notebooks \
    -v ${PWD}/data:/root/analysis/data \
    -v ${HOME}/.vimrc:/root/.vimrc \
    -v ${HOME}/.vim:/root/.vim \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e DISPLAY \
    -e QT_X11_NO_MITSHM=1 \
    --network=host \
    --device /dev/snd \
    --device /dev/input \
    --privileged \
    spirit_dev

xhost -local:root
