camera:
  mock_camera: false  # Default is false.
  show: false  # Default is false.
  real:
    drone_ip: 192.168.1.1  # Default is 192.168.1.1.
    use_tum: false  # Default is false.
  slowdown: 15  # times. Default is 15.

pose:
  mock_pose: false  # Default is false.
  real:
    use_mocap: true  # Default is true.
    use_odometry: false  # Default is false.

past_image:
  eval_method: constant_time_delay
  constant_time_delay:
    delay: 5
  constant_distance:
    distance: 10

visualization:
  show: true
  debug: False  # False, online, offline
