camera:
  mock_camera: false  # Default is false.
  show: true  # Default is false.
  streams:
    realtime: true
    slow: true
    past_image: true
  real:
    drone_ip: 192.168.1.1  # Default is 192.168.1.1.
    use_tum: false  # Default is false.
  slowdown: 15  # times. Default is 15.

pose:
  mock_pose: false  # Default is false.
  real:
    use_mocap: true  # Default is true.
    use_odometry: false  # Default is false.

past_image:
  eval_method: constant_distance
  constant_time_delay:
    delay: 2
  constant_distance:
    distance: 1.5
  murata:
    a1: 1
    a2: 1
    a3: 1
    a4: 1
    a5: 1
    z_ref: 0.2
    l_ref: 1.5

visualization:
  show: true
  debug: False  # False, online, offline
