camera:
  mock_camera: false  # Default is false.
  show: true  # Default is false.
  streams:
    realtime: true
    slow: false
    past_image: false
  real:
    drone_ip: 192.168.1.1  # Default is 192.168.1.1.
  slowdown: 15  # times. Default is 15.

control:
  use_joystick: true  # Default is true.
  js_number: auto  # Default is 1. /dev/input/js1

pose:
  mock_pose: false  # Default is false.
  real:  # Only used if mock_pose is false
    use_mocap: true  # Default is true.
    use_odometry: false  # Default is false.

past_image:
  general:
    eval_method: Spirit  # Default is Spirit.
    image_queue_length: 30  # Use None for infinite.
  Spirit:
    coeff_centrality: 0
    coeff_centrality2: 8
    coeff_direction: 4
    coeff_distance: 8
    coeff_direction_with_current: 1
    coeff_distance_with_current: 2
    ref_distance: 3  # m
    thresh_distance: 0.01  # m
    thresh_yaw: 0.02  # rad
  ConstantDistance:
    coeff_distance: 1
    ref_distance: 1.5
  ConstantTimeDelay:
    coeff_time: 1
    ref_delay: 2
  Murata:
    coeff_height: 2
    coeff_direction: 0.4
    coeff_elevation: 0.8
    coeff_distance: 4
    ref_height: 0.3
    ref_distance: 1.5

visualization:
  show: true
  debug: false  # false, online, offline
